### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by mahsa-frj** [gluster/glusterfs-hadoop#128]
hi
when i execute mvn package, i get error!
Does anyone have problem with mvn package?
please help me. 
thank for your reply

**Comment by jayunit100** [comment]
Hi masha, try `mvn package -DskipTests=true`.  Does that work ? If so the problem is that tests are failing.  This might happen if you don't have some  files/directories write permissions and so on.

Can you paste the failures?

**Comment by mahsa-frj** [comment]
thanks jayunit100, both mvn package and mvn package -DskipTests=true have problem. after downloading packages i get this messages 
[info] [GitCommitIdMojo] git.commit.id = f0fee73c336ac19461d5b5bb91a77e05cff73361
[info] [GitCommitIdMojo] git.commit.message.short = Merge pull request #122 from childsb/getfattrparse
[info] [GitCommitIdMojo] git.commit.user.name = bradley childs
[info] [GitCommitIdMojo] git.build.user.name = Unknown
[info] [GitCommitIdMojo] git.commit.id.describe = GA-12-gf0fee73
[info] [GitCommitIdMojo] git.build.user.email = Unknown
[info] [GitCommitIdMojo] git.branch = master
[info] [GitCommitIdMojo] git.commit.time = 31.03.2015 @ 00:36:46 IRDT
[info] [GitCommitIdMojo] git.build.time = 06.04.2015 @ 18:43:29 IRDT
[info] [GitCommitIdMojo] ---------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:52.096s
[INFO] Finished at: Mon Apr 06 18:43:29 IRDT 2015
[INFO] Final Memory: 14M/115M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.1.4:revision (default) on project glusterfs-hadoop: Execution default of goal pl.project13.maven:git-commit-id-plugin:2.1.4:revision failed: Cannot create custom git properties file: src/main/resources/git.properties: Unable to create parent directories of /home/ossl/glusterfs/glusterfs-hadoop/src/main/resources/git.properties -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

i have write permissions.

**Comment by jayunit100** [comment]
can you run `mkdir -p /home/ossl/glusterfs/glusterfs-hadoop/src/main/resources/` and open permissions to 777 on it, just to confirm  ?

**Comment by jayunit100** [comment]
for context, that build plugin attempts to write `git.properties` to the above dir.  if that dir cant be created, or else, can't be read, then an error will ensue.

**Comment by mahsa-frj** [comment]
thanks for your help, i created this directory, some problems are configured, but i have 93 errors yet!!
Results :

Tests in error: 
  org.apache.hadoop.fs.test.unit.HcfsUmaskTest: java.lang.reflect.InvocationTargetException
  org.apache.hadoop.fs.test.unit.HcfsUmaskTest
  testMkdirsFailsForSubdirectoryOfExistingFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testMkdirsFailsForSubdirectoryOfExistingFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWDAbsolute(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWDAbsolute(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusThrowsExceptionForNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusThrowsExceptionForNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testDeleteNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testDeleteNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testFsStatus(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testFsStatus(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWorkingDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWorkingDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testMkdirs(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testMkdirs(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGetFileStatusThrowsExceptionForNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGetFileStatusThrowsExceptionForNonExistentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testListStatus(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testListStatus(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testListStatusFilterWithNoMatches(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testListStatusFilterWithNoMatches(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusWithNoMatchesInPath(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusWithNoMatchesInPath(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusSomeMatchesInDirectories(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusSomeMatchesInDirectories(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusWithMultipleWildCardMatches(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusWithMultipleWildCardMatches(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusWithMultipleMatchesOfSingleChar(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusWithMultipleMatchesOfSingleChar(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithEmptyPathResults(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithEmptyPathResults(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithSomePathMatchesAndTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithSomePathMatchesAndTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithMultipleWildCardMatchesAndTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithMultipleWildCardMatchesAndTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithMultiplePathMatchesAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithMultiplePathMatchesAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithNoMatchingPathsAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithNoMatchingPathsAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testGlobStatusFilterWithMultiplePathWildcardsAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testGlobStatusFilterWithMultiplePathWildcardsAndNonTrivialFilter(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteReadAndDeleteEmptyFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteReadAndDeleteEmptyFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteReadAndDeleteHalfABlock(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteReadAndDeleteHalfABlock(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteReadAndDeleteOneBlock(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteReadAndDeleteOneBlock(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteReadAndDeleteOneAndAHalfBlocks(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteReadAndDeleteOneAndAHalfBlocks(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteReadAndDeleteTwoBlocks(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteReadAndDeleteTwoBlocks(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testOverwrite(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testOverwrite(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testWriteInNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testWriteInNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testDeleteRecursively(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testDeleteRecursively(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testDeleteEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testDeleteEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameNonExistentPath(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameNonExistentPath(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileToNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileToNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileToDestinationWithParentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileToDestinationWithParentFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileToExistingParent(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileToExistingParent(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileToItself(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileToItself(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileAsExistingFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileAsExistingFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameFileAsExistingDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameFileAsExistingDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryToItself(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryToItself(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryToNonExistentParent(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryToNonExistentParent(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryAsNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryAsNonExistentDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryAsEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryAsEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryAsNonEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryAsNonEmptyDirectory(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testRenameDirectoryAsFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testRenameDirectoryAsFile(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testInputStreamClosedTwice(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testInputStreamClosedTwice(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testOutputStreamClosedTwice(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest): java.lang.reflect.InvocationTargetException
  testOutputStreamClosedTwice(org.apache.hadoop.fs.test.unit.HcfsMainOperationsBaseTest)
  testDefaultPath(org.apache.hadoop.fs.test.unit.GlusterMultipleVolumeTest): java.lang.reflect.InvocationTargetException
  org.apache.hadoop.fs.test.unit.HcfsFileSystemTest: java.lang.reflect.InvocationTargetException
  org.apache.hadoop.fs.test.unit.HcfsFileSystemTest

Tests run: 98, Failures: 0, Errors: 93, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.737s
[INFO] Finished at: Tue Apr 07 09:43:38 IRDT 2015
[INFO] Final Memory: 36M/337M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project glusterfs-hadoop: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ossl/glusterfs/glusterfs-hadoop/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

i try to solve this problem, but i can't...

**Comment by mahsa-frj** [comment]
my problem solved. thanks, but i use hadoop-1... and glusterfs 3.5.3, after mvn package finish i copy jar file into hadoop library. i start hadoop without any problem, but when i use this command:
hadoop fs -mkdir /test
i get this error:
[root@fedora1 hadoop-root]# hadoop fs -mkdir /hadoop
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/04/08 12:56:29 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/04/08 12:56:29 INFO glusterfs.GlusterFileSystem: Initializing GlusterFS,  CRC disabled.
15/04/08 12:56:29 INFO glusterfs.GlusterFileSystem: GIT INFO={git.commit.id.abbrev=f0fee73, git.commit.user.email=bchilds@redhat.com, git.commit.message.full=Merge pull request #122 from childsb/getfattrparse

Refactor and cleanup the BlockLocation parsing code, git.commit.id=f0fee73c336ac19461d5b5bb91a77e05cff73361, git.commit.message.short=Merge pull request #122 from childsb/getfattrparse, git.commit.user.name=bradley childs, git.build.user.name=Unknown, git.commit.id.describe=GA-12-gf0fee73, git.build.user.email=Unknown, git.branch=master, git.commit.time=31.03.2015 @ 00:36:46 IRDT, git.build.time=08.04.2015 @ 12:46:23 IRDT}
15/04/08 12:56:29 INFO glusterfs.GlusterFileSystem: GIT_TAG=GA
15/04/08 12:56:29 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Gluster volume: test at : /mnt/Hadoop
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Working directory is : /
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Write buffer size : 131072
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Default block size : 67108864
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: Directory list order : fs ordering
15/04/08 12:56:29 INFO glusterfs.GlusterVolume: File timestamp lease significant digits removed : 0
mkdir: Error undefined volume:fedora1.osslab.com:9010 in path: glusterfs://fedora1.osslab.com:9010/hadoop

my gluster works true.
thank for your help.
