### ISSUE TITLE
start-all.sh problem with glusterfs

### ISSUE THREAD

**Issue by mahsa-frj** [gluster/glusterfs-hadoop#129]
hi, i use glusterfs 3.5.3 and hadoop 2.2.0 and make jar file and copy them to hadoop library. 
and my core-site.xml is:

<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>

<property>
<name>fs.glusterfs.impl</name>
<value>org.apache.hadoop.fs.glusterfs.GlusterFileSystem</value>
</property>

<property>
<name>fs.default.name</name>
<value>glusterfs://fedora1.osslab.com:9010</value>
</property>

<property>
<name>fs.AbstractFileSystem.glusterfs.impl</name>
<value>org.apache.hadoop.fs.local.GlusterFs</value>
</property>

<property>
<name>fs.glusterfs.volumes</name>
<value>test</value>
</property>
<property>
<name>fs.glusterfs.volume.fuse.test</name>
<value>/mnt/Hadoop</value>
</property>
</configuration>

but when i use start-all script, i get this error:

Starting namenodes on []
fedora3.osslab.com: starting namenode, logging to /var/log/hadoop-hdfs/hadoop-root-namenode-fedora3.osslab.com.out
fedora3.osslab.com: starting datanode, logging to /var/log/hadoop-hdfs/hadoop-root-datanode-fedora3.osslab.com.out
Starting secondary namenodes [fedora1.osslab.com]
fedora1.osslab.com: starting secondarynamenode, logging to /var/log/hadoop-hdfs/hadoop-root-secondarynamenode-fedora1.osslab.com.out
fedora1.osslab.com: Exception in thread "main" java.lang.IllegalArgumentException: Invalid URI for NameNode address (check fs.defaultFS): glusterfs://fedora1.osslab.com:9010 is not of scheme 'hdfs'.
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:353)
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:335)
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.NameNode.getServiceAddress(NameNode.java:328)
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.initialize(SecondaryNameNode.java:235)
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.<init>(SecondaryNameNode.java:199)
fedora1.osslab.com:     at org.apache.hadoop.hdfs.server.namenode.SecondaryNameNode.main(SecondaryNameNode.java:652)
starting yarn daemons
starting resourcemanager, logging to /var/log/hadoop-yarn/yarn-yarn-resourcemanager-fedora1.osslab.com.out
fedora3.osslab.com: starting nodemanager, logging to /var/log/hadoop-yarn/yarn-yarn-nodemanager-fedora3.osslab.com.out

the secondary namenode has problem with glusterfs.
does anyone have this problem?
thanks for your reply.

**Comment by jayunit100** [comment]
Hi.  Why are you using startall.sh?  Name nodes aren't required and
shouldnt be used at all if your using gluster hadoop setup as your file
system.

Make sure to only start yarn daemons and leave the name nodes out of the
picture .

**Comment by mahsa-frj** [comment]
thanks  jayunit100, i use start-yarn.sh and don't have problem, 
[root@fedora1 sbin]# start-yarn.sh 
starting yarn daemons
starting resourcemanager, logging to /var/log/hadoop-yarn/yarn-yarn-resourcemanager-fedora1.osslab.com.out
fedora3.osslab.com: starting nodemanager, logging to /var/log/hadoop-yarn/yarn-yarn-nodemanager-fedora3.osslab.com.out

BUT i want to execute wordcount program and i need make directory in fs, when i use this command, /usr/bin/hadoop fs -mkdir wordcountIN, i get this output:

[root@fedora1 sbin]# /usr/bin/hadoop fs -mkdir wordcountIN
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/04/13 10:17:13 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/04/13 10:17:13 INFO glusterfs.GlusterFileSystem: Initializing GlusterFS,  CRC disabled.
15/04/13 10:17:13 INFO glusterfs.GlusterFileSystem: GIT INFO={git.commit.id.abbrev=f0fee73, git.commit.user.email=bchilds@redhat.com, git.commit.message.full=Merge pull request #122 from childsb/getfattrparse

Refactor and cleanup the BlockLocation parsing code, git.commit.id=f0fee73c336ac19461d5b5bb91a77e05cff73361, git.commit.message.short=Merge pull request #122 from childsb/getfattrparse, git.commit.user.name=bradley childs, git.build.user.name=Unknown, git.commit.id.describe=GA-12-gf0fee73, git.build.user.email=Unknown, git.branch=master, git.commit.time=31.03.2015 @ 00:36:46 IRDT, git.build.time=12.04.2015 @ 14:45:49 IRDT}
15/04/13 10:17:13 INFO glusterfs.GlusterFileSystem: GIT_TAG=GA
15/04/13 10:17:13 INFO glusterfs.GlusterFileSystem: Configuring GlusterFS
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Initializing gluster volume..
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Gluster volume: test at : /mnt/Hadoop
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Working directory is : /
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Write buffer size : 131072
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Default block size : 67108864
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: Directory list order : fs ordering
15/04/13 10:17:13 INFO glusterfs.GlusterVolume: File timestamp lease significant digits removed : 0
-mkdir: Fatal internal error
java.lang.RuntimeException: Error undefined volume:fedora1.osslab.co:9010 in path: glusterfs://fedora1.osslab.co:9010/wordcountIN
    at org.apache.hadoop.fs.glusterfs.GlusterVolume.pathToFile(GlusterVolume.java:242)
    at org.apache.hadoop.fs.glusterfs.GlusterVolume.pathToFile(GlusterVolume.java:235)
    at org.apache.hadoop.fs.glusterfs.GlusterVolume.getFileStatus(GlusterVolume.java:376)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
    at org.apache.hadoop.fs.FileSystem.globStatusInternal(FileSystem.java:1701)
    at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1647)
    at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1622)
    at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:326)
    at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:224)
    at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:207)
    at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:190)
    at org.apache.hadoop.fs.shell.Command.run(Command.java:154)
    at org.apache.hadoop.fs.FsShell.run(FsShell.java:255)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
    at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
    at org.apache.hadoop.fs.FsShell.main(FsShell.java:305)

i google it but could not solve my problem, please help me, this project is important for me.
thanks for your reply.

**Comment by cb200664** [comment]
do you solve the problems ? i user glusterfs:///  it's ok , it's really right?
